# Original: https://github.com/guysoft/OctoPi-Klipper-CustomPiOS/blob/6a88c12f562be4668e26fe89a445e761be1481ac/LICENSE
# License: GPL-3.0
name: build binary

on:
  push:
    branches:
    - "build-*"
    tags:
    - "v*"

jobs:
  # next run all the board builds
  build:
    runs-on: ubuntu-24.04-arm
    steps:
    - name: Checkout Project Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        show-progress: false

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt-get install -y gcc libgpiod-dev p7zip-full

    - name: create a reasonable tag for this run - either a short sha or the tag we were called with
      id: tag
      run: |
        export tag=""
        export is_release="test"
        if [ "${{ github.ref_type }}" = "tag" ] ; then tag="${{ github.ref_name }}" ; else tag="${{ github.sha }}" ; fi
        if [[ "$tag" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]] ; then is_release="release" ; fi
        if [[ "$tag" =~ ^v[0-9]+\.[0-9]+\.[0-9]+-beta ]] ; then is_release="beta" ; fi
        export better_tag=$(echo $tag | sed -r 's/^(.{8}).{32}$/g-\1/')
        echo "tag=${better_tag}" >> $GITHUB_OUTPUT
        echo "is_release=${is_release}" >> $GITHUB_OUTPUT

    - name: Build Image
      id: build
      run: |
        gcc --static -o dht src/main.c src/DHT.c -Iinclude -lgpiod


    - name: Upload to GitHub as release
      uses: softprops/action-gh-release@v2
      if: ${{ steps.tag.outputs.is_release == 'release' }}
      with:
        token: ${{ secrets.PAT_GITHUB_TOKEN }}
        generate_release_notes: true
        body_path: release-notes.md
        files: dht


    - name: Upload to GitHub as beta release
      uses: softprops/action-gh-release@v2
      if: ${{ steps.tag.outputs.is_release == 'beta' }}
      with:
        token: ${{ secrets.PAT_GITHUB_TOKEN }}
        generate_release_notes: true
        body_path: release-notes.md
        prerelease: true
        files: dht

